name: Linux CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shell script
        env:
          APP_NEW: production
        run: |
          echo "Environment is $APP_ENV"
          chmod +x hello.sh
          ./hello.sh

