name: Linux CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build step
        run: |
          echo "Building application..."
          chmod +x hello.sh
          ./hello.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step
        env:
           DEPLOY_ENV: ${{ secrets.DEPLOY_ENV }}
        run: |
            echo "Deploying to $DEPLOY_ENV environment"
            echo "Deployment successful"
